version: "3"
services:
        jupyter:
                build: .
                volumes:
                        - ./:/tmp/working
                working_dir: /tmp/working
                ports:
                        - 8888:8888
                environment:
                        - NVIDIA_VISIBLE_DEVICES=all
                        - NVIDIA_DRIVER_CAPABILITIES=all
                command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
